baseURL = ""
languageCode = "en-us"
title = "The Paradox _of Open"

theme = "essay"
disableKinds = ["RSS", "sitemap", "section", "taxonomy", "term", "robotsTXT"]

[params]
  email = "hello@openfuture.eu"
  logo_image = "/images/logo.svg"
  footer = "All content is published in the Public Domain  \nRead our statues."
  credits =  "by Paul Keller  \n& Alek Tarkowski"